# Generated by Django 4.2.2 on 2023-07-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('numloc', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_loc', models.CharField(max_length=50)),
                ('design_voiture', models.CharField(max_length=20)),
                ('Nombre_Jours', models.IntegerField(max_length=15)),
                ('Taux_Journalier', models.IntegerField(max_length=20)),
            ],
        ),
    ]
